### PR TITLE
Fix for LPE definitions

### PR DESCRIPTION
**Pull request by jdent02**
Rest of the code looks good.  Proper outputs were generated.

### CODE REVIEW

**Comment by bsavery** [comment]
Ok I also noticed the PxrSurface lobes weren't working right the other day?  Or maybe I'm misremembering

**Comment by jdent02** [comment]
Okay.  I'll check it out.

**Comment by jdent02** [comment]
Something is wrong with PxrSurface lobes but I don't think it's the exporter.  I set up a material with diffuse, primary and secondary specular, iridescence and clear coat enabled.  Even when I directly copy the LPE from the Renderman docs i get a black screen for every lobe option I can use with that material.  Regular LPE's work fine.  Is there some step to enable the PxrSurface lobe's that we aren't doing?  Or is this a Renderman bug?

**Comment by bsavery** [comment]
I'll check with brenton tomorrow.

**Pull request merged**
