### PR TITLE
export Renderman Shading properties per object

### PR DESCRIPTION
**Pull request by rendermouse**
Added RIB attribute output for Shading Rate, Interpolation, Motion and Focus per object.  Please review.

### CODE REVIEW

**Comment by rendermouse** [comment]
If these look good, I can hook up the Visibility props next.

**Comment by bsavery** [comment]
Actually I think the smooth vs constant interpolation were referring to this. 
https://renderman.pixar.com/resources/current/RenderMan/attributes.html#rishadinginterpolation

Not sure why someone would want to do constant...

**Comment by rendermouse** [comment]
Gotcha. I'll fix that.

**Comment by bsavery** [comment]
Thanks.  I think you can just resubmit the pull request with the changes.

**Comment by MWY3510** [comment]
Just a note, all you have to do is push the latest to your repository and it is automatically added to the pull request. Thanks for all the work rendermouse.

**Comment by rendermouse** [comment]
There is a "photon" visibility attribute, but according to the docs, that is REYES-only. Can you confirm this?

**Comment by bsavery** [comment]
Yeah, I would redo the visibilty attributes.  You could do use the indirect and direct visibility and camera, simplify things.

**Comment by bsavery** [comment]
You know what we really need in the object properties here is single vs double sided. The way that maya does it is they have a single vs double sided property and if single sided you can reverse the sidedness

**Comment by rendermouse** [comment]
Would that be an RiSides setting? Checking a "single-sided" box would reduces 2-sided to 1.
http://renderman.pixar.com/resources/current/RenderMan/risAttributes.html#sides

**Pull request merged**
