### PR TITLE
Texture support for OSL shaders

### PR DESCRIPTION
**Pull request by MWY3510**
Rough and non-optimized

### CODE REVIEW

**Comment by bsavery** [comment]
Hmmm... so this seems to be pretty much the complete opposite of how regular textures are created no?  Meaning instead of getting the names of textures through the nodetree, the nodetree when generating parameters calls txmake.  What's the thought process here?

**Comment by MWY3510** [comment]
Ok, I was not thinking clearly earlier today and just went on a complete get it done mentality. I'm sorry for submitting such badly integrated code. I am working on a better way tonight it should be done shortly. I had a strange day yesterday so that might have been part of the problem. Sorry again.
MWY3510

**Comment by bsavery** [comment]
Oh no worries, I appreciate all the help.  Sorry I haven't had more input, still working on the export code rewrite.

**Comment by MWY3510** [comment]
Ok, I found a way to do texture export using the existing system. I just need to pass a few more parameters to the get_textures function. Hopefully this works and I can dispose of the hack.

**Comment by MWY3510** [comment]
This should be more inline with the plugin design. I also ran some tests and it is faster than the other method too.

**Comment by bsavery** [comment]
Great!

**Comment by MWY3510** [comment]
Basic OSL node reload is almost done probably tomorrow it will be done.

**Pull request merged**
