### PR TITLE
UI changes for upcoming features.

### PR DESCRIPTION
**Pull request by MWY3510**
Let me know if there are any questions.

### CODE REVIEW

**Comment by MWY3510** [comment]
Just a quick question. Is there a reason that we should use IT over multires for interactive rendering?

**Comment by bsavery** [comment]
So the outpath in preferences.py is redundant now no?  Not a big deal.  

'IT' will have better performance displaying interactive rendering than multires. But it would be fine to use multires when 'IT' isn't there...

We should touch base on what you're working on, just so we're not overlapping.

**Comment by MWY3510** [comment]
Currently I am working on a couple of things. First, adding txmake options to nodes with input textures (Repeat x, Repeat y, etc.). Two, getting particle instanced objects to work (I like dupli objects that are spread by the randomness of particles). Three fixing general bugs in the strand system (I still have a hard limit of 20,000 or so for some reason).

Out of curiosity, what are you working on?

**Comment by bsavery** [comment]
Ok that's great.  I'm basically trying to get things stable and completeish for a 1.0 at siggraph.  If you have any ideas about speeding up hair ribgen that would be great too.  I looked at that last week, and found some things.  For example putting a bunch of Ri.Curve calls all into one seemed to make things slower in fact.

So other than just fixing stuff that comes up which there is a ton of I had one other big idea about making ribgen faster which is where I'd like to focus.  The ribgen system now is ok, and I like how it outputs the geometry first and calls read archive.  However what we should do is write those rib archives to a separate file under archives/geometry.rib, or give each geometry it's own file.  The way we do it in RMS is make a big zip file geometry.zip where each geometry has it's own separate part of the zip file.  This would allow three things.  
1.  It would allow static geometry to be ribgen'ed once for many frames.
2.  I have an idea about not ribgenning objects that have not been updated.  There's no concept in blender that I can see of saving the date of the last update on an object.  However if you added a handler to the scene similar to how we  do with interactive rendering, you can monitor all the objects and any time one is updated you can set an update time in the renderman attributes.  This would allow you to only ribgen the objects that have been updated and vastly speed up ribgen time.  Note that materials would still be output each render
3.  A couple people have been asking for a way to "bake out" the geometry archive.

**Comment by bsavery** [comment]
BTW I set the default txmake to periodic the other day (repeat in xy)

**Comment by MWY3510** [comment]
Thanks,
I will take a look at stands today and see if I can improve that. I will also add the option for slicing to the hair I think (Render speed up). For other speed ups, have you looked at compiling parts of the plugin? Also what do you mean about baking out the archive (we already can just export the rib file?)

**Comment by bsavery** [comment]
So in terms of compiling things. The to generation on the backend is a c Python module (import prman loads a compiled module). The one thing I could think that would make a big difference would be generating hair at render time with a compiled procedural. But maybe not a huge difference. Either way I think if we optimized the hair generation in Python now it would be good enough for the time being

There is a feature for exporting an object as a rib arrive already. But don't think it works.

**Comment by MWY3510** [comment]
I check out the export rib option it does export the rib file but not any differently than the export for render.

**Pull request merged**
