### PR TITLE
Add thread flag to Denoise options

### PR DESCRIPTION
**Pull request by MWY3510**

### CODE REVIEW

**Comment by JeannotLandry** [comment]
Is this already implemented?

If so it isn't working because I got the latest version of the addon (downloaded a few minutes ago to test the animated texture sequence rendering) and the denoiser is still maxing my CPU.

So my guess is that it isn't yet, but I thought I'd ask just in case.

**Comment by bsavery** [comment]
Should be:
https://github.com/bsavery/PRMan-for-Blender/blob/master/engine.py#L408

On Sun, Apr 24, 2016 at 11:21 AM, JeannotLandry <notifications@github.com>
wrote:

> Is this already implemented?
>
> If so it isn't working because I got the latest version of the addon
> (downloaded a few minutes ago to test the animated texture sequence
> rendering) and the denoiser is still maxing my CPU.
>
> So my guess is that it isn't yet, but I thought I'd ask just in case.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/pull/240#issuecomment-214017126>
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by bsavery** [comment]
It uses the prman thread setting, which by defualt is -1 (all cores -1)

On Sun, Apr 24, 2016 at 11:22 AM, Brian Savery <brian.savery@gmail.com>
wrote:

> Should be:
> https://github.com/bsavery/PRMan-for-Blender/blob/master/engine.py#L408
>
> On Sun, Apr 24, 2016 at 11:21 AM, JeannotLandry <notifications@github.com>
> wrote:
>
>> Is this already implemented?
>>
>> If so it isn't working because I got the latest version of the addon
>> (downloaded a few minutes ago to test the animated texture sequence
>> rendering) and the denoiser is still maxing my CPU.
>>
>> So my guess is that it isn't yet, but I thought I'd ask just in case.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bsavery/PRMan-for-Blender/pull/240#issuecomment-214017126>
>>
>
>
>
> --
> brian.savery@gmail.com
> 508-274-8700
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by JeannotLandry** [comment]
Brain, the default settings for rendering of -1 brings my CPU to 88 %, but denoiser still brings my CPU to 99%.

**Comment by JeannotLandry** [comment]
I'll try with -2 see if it'll make a difference.

**Comment by bsavery** [comment]
You might try setting it manually to however many cores you have on your
system

i.e. if you have 8 cores set it to 7 or 6

On Sun, Apr 24, 2016 at 11:33 AM, JeannotLandry <notifications@github.com>
wrote:

> I'll try with -2 see if it'll make a difference.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/pull/240#issuecomment-214020364>
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by JeannotLandry** [comment]
I'll give that a quick try. I've tested it with -4 and same thing, PRMan took 48% of CPU and the denoiser took 99%. I'll try entering the number instead of the -1 and let you know.

**Comment by JeannotLandry** [comment]
Yup, that worked, I've set it to 6 (I have 8 cores) and PRMan took 75% of the CPU and the Denoiser as well :) So it doesn't work with the - feature, but it works if you set it manually with a positive number :)

This will have to be specified in the documentation once that is on the way ;) Awesome :) Thanks Brian.

Unrelated question, I would like a to create a few video tutorials to help people get started with this amazing addon and renderman non-commercial. Any ideas on subjects that could be helpful for everyone? If you want you can e-mail me directly on this (acadian.lapino@gmail.com)

**Comment by MWY3510** [comment]
Brian, unless you have a major concern I will merge this item.

**Pull request merged**
