### PR TITLE
Speed up the pipeline and prevent unnecessary texture conversion.

### PR DESCRIPTION
**Pull request by MWY3510**
Let me know if you have any questions. This has been tested on windows and should work on other platforms.

### CODE REVIEW

**Comment by bsavery** [comment]
So I thought about this. Here's the issue. And I'm on mobile so maybe I didn't get all the code changes.  But what if the image file to be converted is updated?  It looks like a new texture is not created?  You could check the time stamps of files to be more robust. Also you'd have to account for the case of changing texture conversion options...

**Comment by MWY3510** [comment]
Ok, What I added was a button that is also checked before txmake is called it is called always recompile textures. I could by default have it on and if you do many rerenders with the same textures then it could be checked off. Also what do you mean by texture conversion options?

**Comment by bsavery** [comment]
I would add a check to see if the input image file mod time is newer than the tex mod time.  By default you could only make texture if the image is modified newer than the texture.

**Comment by MWY3510** [comment]
Added the check. Let me know if there is anything else that could improve the texture pipeline. For now it should be stable but I can only run tests on windows. After I get the curves pipeline sorted I will ask on the forum about having others test the new additions. Let me know if you want me to tackle any other features while you are away.

**Comment by bsavery** [comment]
You might want to take a look at the tamale options.  I think you can tie that through the texture panel options somehow. Either way I think Matt had code in export.py originally for that.

**Pull request merged**
