### PR TITLE
Add strands, curves and improvments across the board.

### PR DESCRIPTION
**Pull request by MWY3510**
Whew I am glad that this is compiled and ready. These changes have been tested with three different demo files that I am working on focusing on pushing the limits of the exporter. All changes work well on windows. Please let me know if you have any questions.

### CODE REVIEW

**Comment by bsavery** [comment]
Ok couple thoughts. 

1.  Why t:1 on renders?  Was that a typo?
1a. I see you changed the min max samples. Maybe because you set t:1?  We can debate what the correct min max defaults are. Those are what Pixar uses in rms I think. Either way you should use squares there. 4, 16, 64 etc

2.  Supported_material_types was this the right name here?  Maybe supported curve types. 

Sorry for the late vague reply I'm on mobile. Debug stuff looks great.

**Comment by MWY3510** [comment]
Good evening,
     1. The t:1 was a typo. The min and max samples were set in one of AtomicP's commits so I did not notice it. What are the recommended values you think?

    2. The supported_material_types was also something I did not notice. It has been changed to supported_mesh_types.

**Comment by bsavery** [comment]
T:-1 is the way to go. It sets the number of threads to number of cores -1
which makes sense here as you'd want one for updating the display.

Whatever I had previously as the min/max samples are what we use in rms and
rfk


On Tuesday, June 30, 2015, MWY3510 <notifications@github.com> wrote:

> Good evening,
> 1. The t:1 was a typo. The min and max samples were set in one of
> AtomicP's commits so I did not notice it. What are the recommended values
> you think?
>
> 2. The supported_material_types was also something I did not notice. It has been changed to supported_mesh_types.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/pull/6#issuecomment-117391163>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by MWY3510** [comment]
Ok coming right up :-) .

**Comment by MWY3510** [comment]
Fixes made let me know if there is anything else. The child strands might get added before this pull request is closed just so you know.

**Comment by MarshallRoss** [comment]
Just checking...are nurbs supported now?

**Comment by MWY3510** [comment]
MarshallRoss, at the moment no. I don't know when that will happen. Sorry.

**Comment by MarshallRoss** [comment]
@MWY3510  Hey, no worries.  I was just checking because blender crashed when I tried to render a nurbs cone.  I figured nurbs weren't implemented, and I think they're kinda old school anyway, am I right?  Does Pixar use nurbs for anything, or has the industry more or less gone over to subdivision surfaces?

**Comment by MWY3510** [comment]
I really should add a check to prevent crashes like that from happening. Thanks for mentioning that. As for nurbs surfaces I don't know what pixar's stance on that is but in the geometry primitives page there is an entry for RiPatch. http://renderman.pixar.com/resources/current/RenderMan/geometricPrimitives.html#ripatch

**Comment by bsavery** [comment]
Mostly subdivs

On Wednesday, July 1, 2015, MWY3510 <notifications@github.com> wrote:

> I really should add a check to prevent crashes like that from happening.
> Thanks for mentioning that. As for nurbs surfaces I don't know what pixar's
> stance on that is but in the geometry primitives page there is an entry for
> RiPatch.
> http://renderman.pixar.com/resources/current/RenderMan/geometricPrimitives.html#ripatch
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/pull/6#issuecomment-117675583>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Pull request merged**
