### PR TITLE
Internal rendering will load all output images

### PR DESCRIPTION
**Pull request by jdent02**
into image editor.  Multilayer images still look wonky, but this appears to be a Blender issue.

### CODE REVIEW

**Comment by bsavery** [comment]
Great idea.  How does this work if you have a sequence of images in the folder path though?  I.e. Image.0001.tif, Image.0001.z.tif, Image.0002.tif, Image.0002.z.tif ....   Might need to do some filtering in there.

**Comment by jdent02** [comment]
From what I can determine it looks at the extension of the files in the images_dir folder and if it's a compatible format it'll import it.  So it should import everything.  I'll double check.

Confession: I didn't write this code.  I found it on the Blender Stack Exchange and tweaked it.

**Comment by jdent02** [comment]
Yep, it loads everything as it's created.  So after a three frame animation with four output images you end up with twelve images in the editor.  I'm not a fan of that happening automatically all the time though (it can lead to a mess of files) so I'll add an option to turn the image import on or off.

**Comment by bsavery** [comment]
I would just change it so it filters the names.

On Friday, June 10, 2016, Jon D <notifications@github.com> wrote:

> Yep, it loads everything as it's created. So after a three frame animation
> with four output images you end up with twelve images in the editor. I'm
> not a fan of that happening automatically all the time though (it can lead
> to a mess of files) so I'll add an option to turn the image import on or
> off.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/pull/279#issuecomment-225261902>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABzffJJaxlMLi_gSw3VWgSjEcpiET040ks5qKa61gaJpZM4IzMjf>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by jdent02** [comment]
What kind of filtering were you thinking?  I don't think filtering by frame number would be a good idea.  If someone rendered out a frame from the middle of their animation nothing would load then.

Basically this is just a shortcut to getting all the output images (including AOV's) into Blender for use in the compositor.  Otherwise a user would have to load each individually.

**Comment by bsavery** [comment]
By filtering I mean instead of every image use scene.####.* where #### is
the frame number

On Friday, June 10, 2016, Jon D <notifications@github.com> wrote:

> What kind of filtering were you thinking? I don't think filtering by frame
> number would be a good idea. If someone rendered out a frame from the
> middle of their animation nothing would load then.
>
> Basically this is just a shortcut to getting all the output images
> (including AOV's) into Blender for use in the compositor. Otherwise a user
> would have to load each individually.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/pull/279#issuecomment-225263252>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABzffF8hUZLL0ee58CenZ7dH6qC3vt8Mks5qKa_2gaJpZM4IzMjf>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by bsavery** [comment]
Or better yet collect the expected image names beforehand.

On Friday, June 10, 2016, Jon D <notifications@github.com> wrote:

> What kind of filtering were you thinking? I don't think filtering by frame
> number would be a good idea. If someone rendered out a frame from the
> middle of their animation nothing would load then.
>
> Basically this is just a shortcut to getting all the output images
> (including AOV's) into Blender for use in the compositor. Otherwise a user
> would have to load each individually.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/pull/279#issuecomment-225263252>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABzffF8hUZLL0ee58CenZ7dH6qC3vt8Mks5qKa_2gaJpZM4IzMjf>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by jdent02** [comment]
Gotcha.

**Pull request closed without merging**
