### PR TITLE
Fix For MESH that has VERTs but not Faces but still makes faces with modifiers

### PR DESCRIPTION
**Pull request by AtomicPerception**

### CODE REVIEW

**Comment by bsavery** [comment]
Ok the geometry change looks ok, I'll have to test it more in depth with more geometry types.  8 max samples is way too low.  Keep in mind people can set the samples what they want but I'd say a max of 128 or 256 might be ok.  With denoise 64 might even be ok

**Comment by bsavery** [comment]
64 for a max number of samples.  I'd like to open the max samples argument up to a wider audience..

**Comment by bsavery** [comment]
I'm going to manually integrate you export change.  Did some things in the main branch to have the default settings much faster.

**Comment by AtomicPerception** [comment]
Brian, I think you missed one of my changes for hasFaces in your manual integration? Line #2054 also needs the hasFaces patch or instance based objects will fail the test.

**Pull request closed without merging**
